### ISSUE TITLE
Radically different node download and upload results as compared to speedtest-cli results?

### ISSUE THREAD

**Issue by dachshund-digital** [steffenmllr/node-red-contrib-speedtest#8]
Radically different node download and upload results as compared to speedtest-cli results?  This did not used to be the case but now is.  The difference is so far apart that the node appears to be broke, and unusable now.

**Comment by dachshund-digital** [comment]
This issue continues and now I am seeing the node generate randomly ECONNRESET errors.  Where in the same OS, same hardware using the speedtest-cli, no issues or errors.  I have a test flow that tests the node, and then 30 seconds later tests via CLI, and over 100s of tests, the download speed reported is grossly inconsistent between node and CLI, where upload speed is closer, but still inconsistent.  At this point this node appears to be completely broken and unusable.

**Comment by dflvunoooooo** [comment]
Same problem here. The result for the download varies a lot (35 - 110 Mbit/s) and never reaches the "true" results (~ 180 Mbit/s) from speedtest in browser or cli or Home Assistant integration. 

Same problem with the "updated" version, but I am somehow not able to open an issue there.

**Comment by braydenhouston** [comment]
Also running into the same issue as well. This node red implementation and its "updated" fork are both displaying lower download numbers compared to the correct results shown in the website and the cli versions. The issue seems to be persistent on all the servers I tried to test. Always under reporting 50-100+Mbps for the download speed. 

Strangely, upload stats seems to be correct in all my tests so far. Results have been within a couple Mbps in all my test comparing to the Web/CLI.

**Comment by braydenhouston** [comment]
Looking into this further, this issue probably boils down to this repo (and subsequent forks) not being up to date for the newest version of the speedtest-net dependency. Currently 2.1.1.

**Comment by steffenmllr** [comment]
Thanks for the report, I've published a new version that takes `2.x` as a dependency. Maybe you get better results with this.

**Comment by dachshund-digital** [comment]
I will test again... if I get any wide variance will request reopen of this issue.

**Comment by pbek** [comment]
I still seem to have issues with node-red-contrib-speedtest 1.1.0.
For me `payload.download.bandwidth` shows `8331019` (about 8 MBit/s) and the download result on the speedtest.net page from `payload.result.url` is 66.65 MBit/s (which is more to the truth).
