### ISSUE TITLE
Dependency Issue with agent-base <6.0.0 and Node-RED 2.0

### ISSUE THREAD

**Issue by sammachin** [steffenmllr/node-red-contrib-speedtest#9]
Hi,

We've detected that your node  has a dependency on an old version of `agent-base (<6.0.0)` , 
These old versions were patching a core node.js function in a way that could break other libraries - including one we started using in Node-RED 2.0 for the HTTP Request node.
Therefore any users that upgrade to Node-RED 2.0 and have your node installed (or later try to install it) will get errors when using the http-request node.

Could you please take a look at your dependencies and see if you can update the versions so that you are no longer dependent on agent-base before version 6.0.0

Note this could be a module that you are using has a dependency on agent-base so you might need to check for updates to that module, to help you we've attached your nodes dependency tree below

More details on this issue and the warning message that is now displayed in Node-RED 2.0.2 are on the forum at link https://discourse.nodered.org/t/node-red-2-0-2-released/48767

```
└─ node-red-contrib-speedtest@1.0.1
   └─ speedtest-net@1.6.2
      ├─ draftlog@1.0.13
      ├─ chalk@2.4.2
      │  ├─ escape-string-regexp@1.0.5
      │  ├─ supports-color@5.5.0
      │  │  └─ has-flag@3.0.0
      │  └─ ansi-styles@3.2.1
      │     └─ color-convert@1.9.3
      │        └─ color-name@1.1.3
      ├─ http-proxy-agent@2.1.0
      │  ├─ agent-base@4.3.0
      │  │  └─ es6-promisify@5.0.0
      │  │     └─ es6-promise@4.2.8
      │  └─ debug@3.1.0
      │     └─ ms@2.0.0
      ├─ https-proxy-agent@3.0.1
      │  ├─ agent-base@4.3.0
      │  └─ debug@3.2.7
      │     └─ ms@2.1.3
      └─ xml2js@0.4.23
         ├─ sax@1.2.4
         └─ xmlbuilder@11.0.1


```

Thanks in advance for looking into this.

Sam 

PS Sorry for the templated issue but we've got a number of nodes with the issue so I'm automating the issue creation.

**Comment by steffenmllr** [comment]
@sammachin thanks for the report. I'm not using node-red anymore but i've updated to the latest speedtest so this should not be an issue anymore.
